### ISSUE TITLE
BUG: Villager Trade Emerald to Coin swap not working.

### ISSUE THREAD

**Issue by Amberslice** [Lightman314/LightmansCurrencyFabric#39] opened 2024-07-11 19:41 UTC
### Minecraft Version

1.20.1

### Fabric Version

15.10

### Lightman's Currency Version

1.20.1-1.0.2.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Villagers are refusing to change their trades and are being retired as a result (joke for you)

Please see config here: 
```
	#Villager Related Settings
#Note: Any changes to villagers requires a full reboot to be applied due to how Minecraft/Forge registers trades.
[villagers]
	#Whether the wandering trader will have additional trades that allow you to buy misc items with money.
	addCustomWanderingTrades=true
	
	#Whether the banker villager profession will have any registered trades. The banker sells Lightman's Currency items for coins.
	addBanker=true
	
	#Whether the cashier villager profession will have any registered trades.. The cashier sells an amalgamation of vanilla traders products for coins.
	addCashier=true
	
	#Villager Trade Modification
	#Note: Changes made only apply to newly generated trades. Villagers with trades already defined will not be changed.
	[villagers.modification]
		#Whether vanilla villagers should have the Emeralds from their trades replaced with coins.
		changeVanillaTrades=true
		
		#Whether villagers added by other mods should have the Emeralds from their trades replaced with coins.
		changeModdedTrades=true
		
		#Whether the wandering trader should have the emeralds from their trades replaced with the default replacement coin.
		changeWanderingTrades=true
		
		#The default coin to replace a trades emeralds with.
		defaultReplacementCoin=lightmanscurrency:coin_gold
		
		#List of replacement coin overrides.
		#Each entry must be formatted as follows: "mod:some_trader_type-lightmanscurrency:some_coin"
		#Every trader not on this list will use the default trader coin defined above.
		replacementCoinOverrides=["minecraft:butcher-lightmanscurrency:coin_iron","minecraft:cartographer-lightmanscurrency:coin_iron","minecraft:farmer-lightmanscurrency:coin_iron","minecraft:fisherman-lightmanscurrency:coin_iron","minecraft:fletcher-lightmanscurrency:coin_copper","minecraft:leatherworker-lightmanscurrency:coin_iron","minecraft:mason-lightmanscurrency:coin_iron","minecraft:shepherd-lightmanscurrency:coin_iron","minecraft:librarian-lightmanscurrency:coin_iron","amethyst_imbuement:crystal_witch-lightmanscurrency:coin_iron]

```
And log file here: https://mclo.gs/QGP4XeJ

Looking forward to finding an answer.

### To Reproduce

unsure here.

### Screenshots/Logs/Crash Reports

https://mclo.gs/QGP4XeJ
[lightmanscurrency-common.txt](https://github.com/user-attachments/files/16182773/lightmanscurrency-common.txt)

**Comment by Lightman314** [comment] 2024-07-11 19:48
Duplicate of #33

**Closed as not planned by Lightman314** 2024-07-11 19:48 UTC
Labels: bug, duplicate
