### ISSUE TITLE
BUG: Restarts unlink trades

### ISSUE THREAD

**Issue by thesleever** [Lightman314/LightmansCurrencyFabric#35] opened 2024-05-29 14:22 UTC
### Minecraft Version

1.20.1

### Fabric Version

0.5.11

### Lightman's Currency Version

1.0.2.3a-1.20.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Restarting the server unlink trades in Item Network Trader

### To Reproduce

1. Place an Item Network Trader, select a trade
2. Restart the server or disconnect and reconnect to singleplayer world
3. Open first page of Network Trader

https://github.com/Lightman314/LightmansCurrencyFabric/assets/57146578/d579f366-19ee-41c3-8c44-0a3ec52c8786

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/15485793/latest.log)

**Comment by Lightman314** [comment] 2024-07-18 17:11
Duplicate of #34

**Closed as not planned by Lightman314** 2024-07-18 17:11 UTC
Labels: bug, fixed in dev
