### ISSUE TITLE
BUG: Duping bug with Modern Dynamics

### ISSUE THREAD

**Issue by KaTulib** [Lightman314/LightmansCurrencyFabric#19] opened 2023-08-25 10:21 UTC
### Minecraft Version

1.19.2

### Fabric Version

0.14.21

### Lightman's Currency Version

1.19.2-1.0.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Modern Dynamics

### Describe the bug

When trying to pipe items into my vending machine using a modern dynamics pipe, the machine will duplicate the item.
it seems to "pull" the item from the pipe while the item is in transit, then recieve the item a second time when the pipe has finished transporting.

A hopper could be used but is incredibly slow and inefficient.

In the mean time we will try something else to fill the machine but i thought i might bring this to your attention

### To Reproduce

install Modern Dynamics and Lightmans currency
place a vending machine, set up a sale and select an input side
use an extractor or attractor to pull the sellable item from a chest
watch the vending machines inventory to see the item arive early
notice the item arive through the pipe again later

### Screenshots/Logs/Crash Reports

i dont think the log has anything interesting to say for this case

**Comment by Lightman314** [comment] 2023-10-29 19:14
To be completely honest, I don't properly understand Fabrics storage API all that well, as it's so much more needlessly complicated that Forge's Item/Fluid/Energy Handler API's...

I have a theory as to what the problem might be, and I'll apply it to the next build, but I make no promises that it will actually resolve the issue. If it doesn't I'm just going to work on the assumption that the issue is with Modern Dynamics itself as it functions as intended on vanilla blocks such as the hopper, which would be using Fabrics intended implementation of their own Storage API.

**Comment by Lightman314** [comment] 2023-10-29 20:11
Hopefully fixed in LC Fabric 1.0.1.1

**Closed as completed by Lightman314** 2023-10-29 20:11 UTC
Labels: bug
